[project]
name = "llm-vector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "touilrihab1", email = "touilrihab241@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "openai>=2.53.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.7.0",
]

[project.scripts]
llm-vector = "llm_vector:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
